name: release-drafter

on:
  workflow_dispatch: ~
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@3f0f87098bd6b5c5b9a36d49c41d998ea58f9348 # v6.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
